web/router.ex
defmodule TechTalks.Router do
  use TechTalks.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :logged_in do
    plug TechTalks.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", TechTalks do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/login", SessionController, :new
    post "/login", SessionController, :create

    scope "/" do
      pipe_through :logged_in

      resources "/videos", VideoController
      get "/videos/:id/present", VideoController, :present
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", TechTalks do
  #   pipe_through :api
  # end
end

lib/tech_talks/endpoint.ex
defmodule TechTalks.Endpoint do
  use Phoenix.Endpoint, otp_app: :tech_talks

  socket "/socket", TechTalks.UserSocket

  # Serve at "/" the static files from "priv/static" directory.
  #
  # You should set gzip to true if you are running phoenix.digest
  # when deploying your static files in production.
  plug Plug.Static,
    at: "/", from: :tech_talks, gzip: false,
    only: ~w(css fonts images js favicon.ico robots.txt)

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Logger

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Poison

  plug Plug.MethodOverride
  plug Plug.Head

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  plug Plug.Session,
    store: :cookie,
    key: "_tech_talks_key",
    signing_salt: "pwF1X0Kx"

  plug TechTalks.Router
end

lib/tech_talks/presence.ex
defmodule TechTalks.Presence do
  use Phoenix.Presence, otp_app: :tech_talks,
                        pubsub_server: TechTalks.PubSub
end

lib/tech_talks/random.ex
defmodule TechTalks.Random do
  @alphabet String.codepoints("ABCDEFGHIJKLMNOPQRSTUVWXYZ")

  def string(length, alphabet \\ @alphabet)
  def string(0, _), do: ""
  def string(length, alphabet) do
    Enum.random(alphabet) <> string(length - 1, alphabet)
  end
end

lib/tech_talks/repo.ex
defmodule TechTalks.Repo do
  use Ecto.Repo, otp_app: :tech_talks
end

lib/tech_talks/session.ex
defmodule TechTalks.Session do
  def start_link do
    Agent.start_link(fn -> %{} end, name: __MODULE__)
  end

  def get_video(session_id) do
    Agent.get(__MODULE__, fn videos ->
      videos[session_id]
    end)
  end

  def set_video(session_id, video) do
    Agent.update(__MODULE__, fn videos ->
      Map.put(videos, session_id, video)
    end)
  end
end

web/models/video.ex
defmodule TechTalks.Video do
  use TechTalks.Web, :model

  schema "videos" do
    field :title, :string
    field :url, :string
    field :description, :string

    timestamps()
  end

  def id(video) do
    ~r/\?v=([^\&]+)/
    |> Regex.run(video.url)
    |> Enum.at(1)
  end

  @doc """
  Builds a changeset based on the `struct` and `params`.
  """
  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :url, :description])
    |> validate_required([:title, :url])
  end
end

web/controllers/page_controller.ex
defmodule TechTalks.PageController do
  use TechTalks.Web, :controller

  def index(conn, _params) do
    render conn, "index.html"
  end
end

web/controllers/session_controller.ex
defmodule TechTalks.SessionController do
  use TechTalks.Web, :controller

  alias TechTalks.Session

  def new(conn, _params) do
    render(conn, "new.html")
  end

  def create(conn, %{"login" => login}) do
    if login["username"] == System.get_env["ADMIN_USERNAME"] && login["password"] == System.get_env["ADMIN_PASSWORD"] do
      conn
      |> TechTalks.Auth.login
      |> put_flash(:info, "Logged in.")
      |> redirect(to: video_path(conn, :index))
    else
      conn
      |> put_flash(:error, "Invalid username or password")
      |> render("new.html")
    end
  end
end

web/controllers/video_controller.ex
defmodule TechTalks.VideoController do
  use TechTalks.Web, :controller

  alias TechTalks.Video

  def index(conn, _params) do
    videos = Repo.all(Video)
    render(conn, "index.html", videos: videos)
  end

  def new(conn, _params) do
    changeset = Video.changeset(%Video{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"video" => video_params}) do
    changeset = Video.changeset(%Video{}, video_params)

    case Repo.insert(changeset) do
      {:ok, _video} ->
        conn
        |> put_flash(:info, "Video created successfully.")
        |> redirect(to: video_path(conn, :index))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    video = Repo.get!(Video, id)
    render(conn, "show.html", video: video)
  end

  def present(conn, %{"id" => id, "session" => session}) do
    video = Repo.get!(Video, id)
    render(conn, "present.html", video: video, session: session)
  end
  def present(conn, %{"id" => id}) do
    session = TechTalks.Random.string(12)
    redirect(conn, to: video_path(conn, :present, id, session: session))
  end

  def edit(conn, %{"id" => id}) do
    video = Repo.get!(Video, id)
    changeset = Video.changeset(video)
    render(conn, "edit.html", video: video, changeset: changeset)
  end

  def update(conn, %{"id" => id, "video" => video_params}) do
    video = Repo.get!(Video, id)
    changeset = Video.changeset(video, video_params)

    case Repo.update(changeset) do
      {:ok, video} ->
        conn
        |> put_flash(:info, "Video updated successfully.")
        |> redirect(to: video_path(conn, :show, video))
      {:error, changeset} ->
        render(conn, "edit.html", video: video, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    video = Repo.get!(Video, id)

    # Here we use delete! (with a bang) because we expect
    # it to always work (and if it does not, it will raise).
    Repo.delete!(video)

    conn
    |> put_flash(:info, "Video deleted successfully.")
    |> redirect(to: video_path(conn, :index))
  end
end

web/views/error_view.ex
defmodule TechTalks.ErrorView do
  use TechTalks.Web, :view

  def render("404.html", _assigns) do
    "Page not found"
  end

  def render("500.html", _assigns) do
    "Internal server error"
  end

  # In case no render clause matches or no
  # template is found, let's render it as 500
  def template_not_found(_template, assigns) do
    render "500.html", assigns
  end
end

web/views/layout_view.ex
defmodule TechTalks.LayoutView do
  use TechTalks.Web, :view
end

web/views/page_view.ex
defmodule TechTalks.PageView do
  use TechTalks.Web, :view
end

web/views/session_view.ex
defmodule TechTalks.SessionView do
  use TechTalks.Web, :view
end

web/views/video_view.ex
defmodule TechTalks.VideoView do
  use TechTalks.Web, :view
  alias TechTalks.Video

  def video_id(video) do
    Video.id(video)
  end
end

web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Tech Talks</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
    <script>
      (function(ctx) {
        let callbacks = [];
        ctx.onInit = function(fn) {
          callbacks.push(fn);
        };
        ctx.init = function() {
          callbacks.forEach(function(fn) {
            fn();
          });
          callbacks = [];
        };
      })(window);
    </script>
  </head>

  <body>
    <div class="container">
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>

      <main role="main">
        <%= render @view_module, @view_template, assigns %>
      </main>

    </div> <!-- /container -->
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>init();</script>
  </body>
</html>

web/templates/page/index.html.eex
<div id="player">
  Loading...
</div>

<script src="https://www.youtube.com/player_api"></script>
<script>
  (function() {
    // Youtube calls `onYouTubePlayerAPIReady` when it finishes loading
    /// the embed iframe. Convert it to a promise for ease of use.
    let awaitYoutube = new Promise(function(resolve, reject) {
      window.onYouTubePlayerAPIReady = function() {
        resolve();
      };
    });

    onInit(function() {
      let Player = require("web/static/scripts/player").default;
      let playerDiv = document.getElementById("player");
      new Player(awaitYoutube, playerDiv);
    });
  }());
</script>

web/templates/session/new.html.eex
<h2>Login</h2>

<%= form_for @conn, session_path(@conn, :create), [as: :login], fn f -> %>
  <div class="form-group">
    <%= label f, :username, class: "control-label" %>
    <%= text_input f, :username, class: "form-control" %>
    <%= error_tag f, :username %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/video/edit.html.eex
<h2>Edit video</h2>

<%= render "form.html", changeset: @changeset,
                        action: video_path(@conn, :update, @video) %>

<%= link "Back", to: video_path(@conn, :index) %>

web/templates/video/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :url, class: "control-label" %>
    <%= text_input f, :url, class: "form-control" %>
    <%= error_tag f, :url %>
  </div>

  <div class="form-group">
    <%= label f, :description, class: "control-label" %>
    <%= textarea f, :description, class: "form-control", rows: 20 %>
    <%= error_tag f, :description %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

web/templates/video/index.html.eex
<h2>Listing videos</h2>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
    </tr>
  </thead>
  <tbody>
<%= for video <- @videos do %>
    <tr>
      <td class="plain"><%= link video.title, to: video_path(@conn, :show, video) %></td>
    </tr>
<% end %>
  </tbody>
</table>

<%= link "New video", to: video_path(@conn, :new) %>

web/templates/video/new.html.eex
<h2>New video</h2>

<%= render "form.html", changeset: @changeset,
                        action: video_path(@conn, :create) %>

<%= link "Back", to: video_path(@conn, :index) %>

web/templates/video/present.html.eex
<div class="prevent-highlight">
  <h3><%= @video.title %></h3>
  <div id="players"></div>

  <%= link "Back", to: video_path(@conn, :show, @video) %>
</div>

<script>
  onInit(function() {
    let Presenter = require("web/static/scripts/presenter").default;
    let playerDiv = document.getElementById("players");
    new Presenter(playerDiv, {session: "<%= @session %>", video: "<%= video_id(@video) %>"});
  });
</script>

web/templates/video/show.html.eex
<h3><%= @video.title %></h3>
<%= link "Present video", to: video_path(@conn, :present, @video) %>

<dl class="video">
  <dt>Link</dt>
  <dd><a href="<%= @video.url %>"><%= @video.url %></a></dd>

  <dt>Description</dt>
  <dd class="description"><%= @video.description %></dd>
</dl>

<div class="links">
  <%= link "All videos", to: video_path(@conn, :index) %>
  <%= link "Edit", to: video_path(@conn, :edit, @video) %>
</div>